# fish_color_normal normal
fish_color_autosuggestion brgreen --dim
# fish_color_cancel --reverse
fish_color_command brmagenta
fish_color_comment brblue --dim
# fish_color_cwd green
# fish_color_cwd_root red
# fish_color_end green
fish_color_error brmagenta --bold --reverse
# fish_color_escape brcyan
# fish_color_history_current --bold
# fish_color_host normal
# fish_color_host_remote yellow
fish_color_keyword brblue
fish_color_operator brcyan
fish_color_option brgreen
fish_color_param brgreen
fish_color_quote bryellow
fish_color_redirection normal --bold
fish_color_search_match brwhite --background=brblack --bold
fish_color_selection brwhite --background=brblack --bold
# fish_color_status red
# fish_color_user green
# fish_color_valid_path --underline

fish_pager_color_completion brgreen --dim
fish_pager_color_description bryellow
fish_pager_color_prefix normal
fish_pager_color_progress magenta --underline
# fish_pager_color_selected_background --reverse
